# Required: local settings
local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

# Required: deployment targets
targets:
  - type     : "bintray" # Options: bintray
    user     : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_USER'] %>
    password : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_API_KEY'] %>

# Required: packages to be deployed
packages:
  - repo     : "snowplow-generic"
    name     : "google-cloud-dataflow-example-project"
    user_org : "snowplow"
    publish  : true

    # Will attempt to overwrite a published entity if one is found
    override : false

    # If the artifact already exists will determine whether or not
    # to fail the release
    continue_on_conflict : false

    # The version of this package
    version  : <%= ENV['TRAVIS_TAG'] %>

    # Required IF '--check-version' is passed: will assert that
    # both versions are the same
    build_version : <%= FUNC['sbt_version(.)'] %>
    
    build_commands:
      - sbt assembly

    # Required: Artifact
    artifacts:
        # The artifact name is composed like so:
        # {{prefix}}{{version}}{{suffix}}.zip
      - prefix : "google-cloud-dataflow-example-project_"
        suffix : ""
        type   : "zip"

        # The binaries to put in the zip
        binary_paths:
          - target/scala-2.11/google-cloud-dataflow-example-project-<%= ENV['TRAVIS_TAG'] %>.jar
